### ISSUE TITLE
Unhandled `java.lang.NullPointerException` on explain-sql-error 

### ISSUE THREAD

**Issue by lucassousaf** [magnetcoop/sql-utils#7]
The `explain-sql-error` thows an `java.lang.NullPointerException` on this [line](https://github.com/magnetcoop/sql-utils/blob/master/src/magnet/sql_utils.clj#L206):
```clj
(re-matches #"^23[0-9P]{3}" sql-state)
```
It seems that `sql-state` can be `null` in some situations. So we could wrap it in a `try/catch` block and return a meaningful error.

**Comment by iarenaza** [comment]
Or we could do an `if-let` in line https://github.com/magnetcoop/sql-utils/blob/master/src/magnet/sql_utils.clj#L190, instead of a simple let.

**Comment by lucassousaf** [comment]
Yep, that sounds good!
